{% set name = "sse-starlette" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sse-starlette-{{ version }}.tar.gz
  sha256: 56d99b475deece2d6b77762c4f5ab924eccb20b24f4a54789edf2497105a6d36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - starlette

test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/sysid/sse-starlette


extra:
  recipe-maintainers:
    - cyprienc
