{% set name = "sse-starlette" %}
{% set version = "1.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e0f9b8dec41adc092a0a6e0694334bd3cfd3084c44c497a6ebc1fb4bdd919acd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - anyio
    - fastapi
    - uvicorn
    - python >=3.8
    - starlette

test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sysid/sse-starlette


extra:
  recipe-maintainers:
    - dhirschfeld
    - cyprienc
