{% set name = "sse-starlette" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2be010484d29a0a1ac6b5ae72610ada3bb00f1be0ef0048a8b87f9dba1e99fcb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - anyio >=4.7.0
    - starlette >=0.41.3
    - uvicorn
test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sysid/sse-starlette


extra:
  recipe-maintainers:
    - dhirschfeld
    - cyprienc
