{% set name = "sse-starlette" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 88cfb08747e16200ea990c8ca876b03910a23b547ab3bd764c0d8eb81019b971

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - anyio >=4.7.0
    - starlette >=0.41.3
test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sysid/sse-starlette


extra:
  recipe-maintainers:
    - dhirschfeld
    - cyprienc
